import { formatPollutant, getPollutantUnit } from './aqiHelpers';
import { GAS_RANGE_KEYS, HEALTH_IDEAL_RANGES } from './constants';

function statusForValue(value, goodMax, invert = false) {
  if (invert) {
    if (value >= 80) return 'good';
    if (value >= 50) return 'moderate';
    return 'poor';
  }
  if (value <= goodMax) return 'good';
  if (value <= goodMax * 1.5) return 'moderate';
  return 'poor';
}

export function buildGasRangeRows(aqiData) {
  if (!aqiData) return [];
  return GAS_RANGE_KEYS.map((key) => {
    const meta = HEALTH_IDEAL_RANGES[key];
    const value = aqiData[key];
    const unit = getPollutantUnit(key);
    return {
      key,
      metric: formatPollutant(key),
      ideal: meta.ideal,
      yours: value == null ? '—' : `${value} ${unit}`,
      value,
      goodMax: meta.goodMax,
      unit,
      status: value == null ? 'moderate' : statusForValue(value, meta.goodMax),
      note: meta.label,
    };
  });
}

export function buildHealthComparison(aqiData, assessment) {
  const rows = [];

  if (aqiData?.aqi != null) {
    rows.push({
      metric: 'Air Quality Index (AQI)',
      ideal: HEALTH_IDEAL_RANGES.aqi.ideal,
      yours: String(aqiData.aqi),
      status: statusForValue(aqiData.aqi, HEALTH_IDEAL_RANGES.aqi.goodMax),
      note: HEALTH_IDEAL_RANGES.aqi.label,
    });
  }

  rows.push(...buildGasRangeRows(aqiData));

  if (assessment?.healthScore != null) {
    rows.push({
      metric: 'Health Score',
      ideal: HEALTH_IDEAL_RANGES.healthScore.ideal,
      yours: String(assessment.healthScore),
      status: statusForValue(assessment.healthScore, 80, true),
      note: HEALTH_IDEAL_RANGES.healthScore.label,
    });
  }

  if (assessment?.riskScore != null) {
    rows.push({
      metric: 'Risk Score',
      ideal: HEALTH_IDEAL_RANGES.riskScore.ideal,
      yours: `${assessment.riskScore}%`,
      status: statusForValue(assessment.riskScore, HEALTH_IDEAL_RANGES.riskScore.goodMax),
      note: HEALTH_IDEAL_RANGES.riskScore.label,
    });
  }

  return rows;
}

export function downloadHealthReport({ profile, assessment, aqiData, weather, location, cityLabel }) {
  const date = new Date().toLocaleDateString('en-IN', { dateStyle: 'long' });
  const comparison = buildHealthComparison(aqiData, assessment);
  const customMed = (profile.customMedical || []).join(', ') || '—';
  const customSym = (profile.customSymptoms || []).join(', ') || '—';

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>SmartAQI Health Report</title>
<style>
  body { font-family: Inter, Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1e293b; }
  h1 { color: #2563eb; } h2 { color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
  th { background: #f1f5f9; }
  .poor { color: #ef4444; font-weight: bold; } .good { color: #22c55e; font-weight: bold; }
  .moderate { color: #f59e0b; font-weight: bold; }
  .header { background: linear-gradient(135deg, #2563eb, #60a5fa); color: white; padding: 24px; border-radius: 12px; margin-bottom: 24px; }
</style></head><body>
<div class="header"><h1 style="color:white;margin:0">SmartAQI Health Report</h1><p style="margin:8px 0 0">${date} · ${cityLabel}, ${location.area}</p></div>
<h2>Patient Information</h2>
<p><strong>Name:</strong> ${profile.name || 'N/A'} | <strong>Age:</strong> ${profile.age} | <strong>Gender:</strong> ${profile.gender}</p>
<p><strong>Other conditions:</strong> ${customMed} | <strong>Other symptoms:</strong> ${customSym}</p>
<h2>Air Quality — ${cityLabel}, ${location.area}</h2>
<p>AQI: <strong>${aqiData.aqi}</strong> | Temp: ${weather?.temp}°C | Humidity: ${weather?.humidity}%</p>
<h2>Gas Ranges — Ideal vs Now</h2>
<table><tr><th>Metric</th><th>Good Range</th><th>Now</th><th>Status</th></tr>
${comparison.map((r) => `<tr><td>${r.metric}</td><td>${r.ideal}</td><td>${r.yours}</td><td class="${r.status}">${r.status.toUpperCase()}</td></tr>`).join('')}
</table>
<h2>Health Assessment Results</h2>
<p><strong>Risk Score:</strong> ${assessment.riskScore}% (${assessment.riskCategory.label})</p>
<p><strong>Health Score:</strong> ${assessment.healthScore}/100</p>
<p>${assessment.aiExplanation}</p>
<h2>Recommendations</h2>
<ul>${assessment.recommendations.map((r) => `<li><strong>${r.title}:</strong> ${r.desc}</li>`).join('')}</ul>
<p style="margin-top:40px;color:#94a3b8;font-size:12px">Generated by SmartAQI — Urban Air Quality Based Respiratory Health Risk Prediction System</p>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.cre